### PR TITLE
Add Flutter snippets

### PR DESCRIPTION
**Pull request by xqwzts**
Adds snippets for Flutter StatelessWidget and StatefulWidget classes

### CODE REVIEW

**Comment by Skylled** [comment]
I love these snippets. I use similar ones in my own setup.

The only concern, as I recall, was being able to have context before offering a snippet. Such as only showing a Flutter snippet when working on a Flutter project. I'm not sure that's yet possible in VS Code.

**Comment by xqwzts** [comment]
@Skylled Looking at this https://github.com/Dart-Code/Dart-Code/issues/350 it seems the way towards context-aware snippets is to use the completion provider.

**Comment by DanTup** [comment]
Yeah; I'd like to move this to the completion provider before adding, so they can be filtered by project type. I want to sort out Angular plugin stuff for v2.7.0, but I'll put this into v2.8.0 and see if I can do it there. It shouldn't be a lot of work.

**Comment by xqwzts** [comment]
Looking forward to it, thanks @DanTup

**Comment by DanTup** [comment]
Flutter snippets will be in the next version (see #474) :)

**Pull request closed without merging**
