### PR TITLE
remove code to work around a pre 1.6 issue

### PR DESCRIPTION
**Pull request by devoncarew**
- remove some pre vscode 1.6 code - hovers in 1.6 better support longer hover docs

@DanTup

### CODE REVIEW

**Comment by DanTup** [comment]
Currently the extension still works with 1.5 so I'm gonna hold off merging this for now (I don't have stats on how fast people update Code - probably should have!).

It's likely I'll will bump the requirement to 1.6 soon (it's already set on the TypeScript v2 branch, and may be required for the targetting terminal work) so this will be valid then.

Keep this open though; it probably won't be long - just don't want to prematurely break 1.5 compatability (without this code the tooltips are unusable) if we ship minor updates before TS2/Debugger work is done.

**Comment by devoncarew** [comment]
> so I'm gonna hold off merging this for now

No worries - no hurry to land :)

**Comment by DanTup** [comment]
I've added the VS Code version to analytics so that it's easier to decide when to do things like this in future.

**Comment by DanTup** [comment]
1.4?!

Code versionsode

**Comment by DanTup** [comment]
Since I can edit your branch now (😁), I've added a change that marks this as requiring Code 1.6 so when this gets merged people won't see the update unless they have >= 1.6.

Will merge this either when a) I can see the huge majority of people are using 1.6 or b) I finish the debugger-targetting-terminal work which also requires it.

**Comment by devoncarew** [comment]
Cool! A practical use of that feature :)

Seems like ~10% are on pre 1.6 versions?

**Comment by DanTup** [comment]
Yeah, just under 10% of sessions for the last week. Annoyingly, I can't find a way to make a graph like the "App Versions" on in analytics (coloured stacked chart) so it's harder to see how quickly people are upgrading without re-running the report for different ranges.

**Comment by DanTup** [comment]
Managed to make an equiv report in Google Data Studio. Didn't really show much with this little data though!

In time it might be handy though.. I should probably migrate the dashboard I created in Analytics to something in there; seems like it can do more :-)

Vode versions

**Comment by DanTup** [comment]
Merged this now... There's the occasional 1.5 session but everything else is 1.6 and 1.7. Many branches are already requiring 1.6 anyway, so requiring 1.6 for the next release seems totally reasonable.

**Pull request merged**
