### PR TITLE
upgrade deps to typescript 2

### PR DESCRIPTION
**Pull request by devoncarew**
- upgrade some deps as specified in the 1.6 release notes
- fix a few new typescript warnings
- fix https://github.com/Dart-Code/Dart-Code/issues/207

### CODE REVIEW

**Comment by DanTup** [comment]
Already got this some of this on a branch (TS upgrade):

https://github.com/Dart-Code/Dart-Code/tree/typescript-v2

I hadn't merged it yet as I'd been playing around with some `strictNullChecks` etc., but it was a can of worms!

I'm away this weekend but will diff this against my TSv2 branch when I can and get this merged; doesn't make sense to hold off the rest of it on the basis of the new features if they're non-trivial.

**Comment by DanTup** [comment]
Btw, #207 was for rolling Code dep too (engine version to 1.7) but I don't think you included this (though I must admit I'm not really sure how the versions for engine and the other deps relate; not sure if certain versions need certain version ranges of others!).

Based on discussions in the Code repo, I'm going to be a bit more aggressive about rolling Code versions forwards - if people are sticking on several-months-old versions of Code then I don't think it's unreasonable they don't get our latest features either!

**Comment by devoncarew** [comment]
Ah, I didn't know about your branch - changes look pretty similar! Feel free to close this one.

But, +1 to rolling this all forward. Totally agree that we can assume most users keep current with VSCode.

**Comment by DanTup** [comment]
Yeah, [the stats](https://datastudio.google.com/open/0B7od1qw9-sxIZXYzWEFVWmJXRDg) generally look good. There's the odd v1.5 session but otherwise they're all newer.

Will diff this against mine before closing to ensure I didn't miss anything (or you did anything in a better way than me). Ta!

**Pull request merged**
