### PR TITLE
did some little code refactor

### PR DESCRIPTION
**Pull request by jokoyoski**
In the refactored code, I extracted the code action objects for organizing imports and sorting members into separate variables. This approach improves readability and eliminates code duplication.

### CODE REVIEW

**Comment by DanTup** [comment]
Thanks! FWIW this code is for the legacy protocol and will eventually be deleted so I wouldn't spend too much time refactoring it. In the new protocol this code lives inside the Dart analysis server (which is hopefully much tidier!):

https://github.com/dart-lang/sdk/blob/11d0f060ef3e34c4a3ed42cbaf554da59e4803ad/pkg/analysis_server/lib/src/lsp/handlers/code_actions/dart.dart#L322

**Review by DanTup — APPROVED** [review]

**Comment by DanTup** [comment]
Looks like there may be some trailing spaces in here that are failing the bots:

```
/home/runner/work/Dart-Code/Dart-Code/src/extension/providers/source_code_action_provider.ts
Error:   25:1  error  Trailing spaces not allowed  no-trailing-spaces
Error:   35:1  error  Trailing spaces not allowed  no-trailing-spaces
Error:   39:1  error  Trailing spaces not allowed  no-trailing-spaces
```

**Comment by jokoyoski** [comment]
@DanTup  kindly check. trailing spaces removed

**Comment by DanTup** [comment]
Looks like there's still one here:

```
/home/runner/work/Dart-Code/Dart-Code/src/extension/providers/source_code_action_provider.ts
Error:   37:1  error  Trailing spaces not allowed  no-trailing-spaces

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

Thanks¬

**Comment by jokoyoski** [comment]
Oh I see. I just removed it. Pls check

**Comment by DanTup** [comment]
Thanks!

**Pull request merged**
