### PR TITLE
Use built-in VSCode API for Telemetry

### PR DESCRIPTION
**Pull request by aitor-gomila**
@DanTup moving #4424 over here.

Using VSCode's built-in logger will be a more concise approach. ~~However, it requires the use of Azure [Application Insights](https://azure.microsoft.com/en-us/products/monitor) for logging instead of the Google-based approach we're using right now.~~

~~I don't like how this API was made - I believe it should be more flexible and Azure should be detached from VSCode.~~

~~However it would be neat to just use this API. What do you think? Should I keep working on it? Is this the approach you/Google/whoever wants?~~

Thanks :)

### CODE REVIEW

**Comment by DanTup** [comment]
> Using VSCode's built-in logger will be a more concise approach. However, it requires the use of Azure [Application Insights](https://github.com/Dart-Code/Dart-Code/pull/4425) instead of the Google-based approach we're using right now.

My understanding is that we can implement a `TelemetryLogger` to send to Google Analytics and do not need to use Azure Application Insights:

https://code.visualstudio.com/api/references/vscode-api#TelemetryLogger

**Comment by DanTup** [comment]
@aitor-gomila the code is already there in the `analytics.ts` file (the code you removed in this PR :-) ). I think it just needs relocating into a `TelemetrySender` class instead (I incorrectly wrote `TelemetryLogger` above where I meant `TelemtrySender`), and then the implementations of the `analytics.logFoo()` methods should become calls to a `TelemteryLogger`.

So generally I think the work is:

- Create a class that extends `TelemetrySender` that uses the code removed in this PR to send the data to Google Analytics (note: we should preserve the existing `debug` flag that lets you send data to the debug endpoint for validation)
- Update where we create the `Analytics` class to instead first create the sender, then call `createTelemetryLogger()`, then pass that logger into the `Analytics` class
- Update the `logXxx` methods on the `Analytics` class to call the `TelemetryLogger`

**Comment by aitor-gomila** [comment]
I removed that code in order to be able to send a PR, restoring it back :)

Ok, that makes a lot of sense. Thanks for clarifying.

**Comment by aitor-gomila** [comment]
Sorry, moving it to another branch. it was getting dirty up there

**Pull request closed without merging**
