### PR TITLE
Flutter packages commands + wiring

### LINKED ISSUE #287: Dart-Code could be able to use flutter packages get instead of pub get
There's a problem currently between Dart and Flutter, and no one seems to really know whose problem it is, so they're suggesting passing it to the editors. See: flutter/flutter#6284

When a project has `flutter: sdk: flutter` in its pubspec.yaml, `pub get` fails with exit code 69.

My plan of attack for this is to follow the template of f7513f95ef72acf49c8eefae58a077aaf3b177bd and make a new `dart.flutterProject` option, and in sdk.ts inside of the on-save hook for pubspec.yaml, have it check whether `dart.flutterProject` is enabled and run `flutter packages get` instead.

If that sounds correct to you, I'll crank it out today.

### PR DESCRIPTION
**Pull request by Skylled**
Fixes #287.

Separated the PRs because this one has a lot more changes by itself.

### CODE REVIEW

**Comment by DanTup** [comment]
This is great; thanks! I'll test and merge as soon as I get a little spare time (if it's not this weekend, next).

**Comment by DanTup** [comment]
I messed up a little merging these in (due to conflicts), but it's all resolved now. Both PRs are merged into master; I'll test/tweak an include in the next release. Thanks again!

**Comment by DanTup** [comment]
@Skylled Btw, I'm sorry I messed up your branch! Best to delete and start over if you want to do any more work on it, the history in my repo is now quite different after I messed up rebasing/squashing!

**Comment by Skylled** [comment]
No worries. I'll be creating new branches for each pull anyway. Just glad to help.

**Comment by DanTup** [comment]
Probably your master will be out of date too (since I quashed the commits into one), so you may want to just delete the repo and re-fork to get up-to-date next time (there's probably an easy way, but I'm no Git ninja, I'm used to Mercurial!).

**Pull request merged**
