### PR TITLE
Add support for running tests from "integration_test" with "flutter test -d deviceId"

### LINKED ISSUE #3009: Integration test with integration_test package
Hello,
I see support to run and debug integration tests using flutter_driver https://github.com/Dart-Code/Dart-Code/pull/2614

There is a new way to write integration tests
https://medium.com/flutter/updates-on-flutter-testing-f54aa9f74c7e
https://flutter.dev/docs/testing/integration-tests

can you please provide some guidance on how to use `flutter drive` command to run and debug integration tests.

Thanks
bsr

### PR DESCRIPTION
**Pull request by DanTup**
- [x] Needs tests
- [ ] Set version number in FlutterCapabilities

Fixes #3009.

### CODE REVIEW

**Comment by jiahaog** [comment]
Thanks! Just tested this out manually (running, debugging) on macOS with a few devices connected and it seems to work great (after patching the version in `src/shared/capabilities/flutter.ts`)! I filed an issue for expression evaluation (https://github.com/flutter/flutter/issues/79439) but other than that are there any other edge cases that we should be concerned about?

**Comment by DanTup** [comment]
Great! I'm not sure if there may be anything else, but perhaps I think I have integration tests here that do a bunch of things for flutter test (inc. expression eval etc.), so maybe I can get them to run over an integration test too to give some more coverage. I'll fix this branch up and work on the tests and let you know if I find any issues.

**Comment by DanTup** [comment]
I've re-tested this and added a few tests, and all seems good to me. Based on https://github.com/flutter/flutter/commit/9e3eadb98d6d5acb5798b2866224f3921706d5e4, I'm setting the version number to enable this as `2.2.0-10` since that changeset appears to first exist in `2.2.0-10.0.pre`.

**Comment by jiahaog** [comment]
Awesome!

**Pull request merged**
