### PR TITLE
Add support for DevTools-server-driven extension recommendations

### PR DESCRIPTION
**Pull request by DanTup**
Adds support for asking DevTools server for any VS Code extension recommendations (which are ready from packages that your workspace depends on).

- [x] Needs tests
- [x] Needs SDK work to land
- [x] Need to verify version number in capabilities
- [x] Need to confirm exact text(/disclaimer?)
- [x] Needs an initial whitelist as part of rollout (empty, can add to later)

image

image

Fixes https://github.com/Dart-Code/Dart-Code/issues/4705

### CODE REVIEW

**Comment by kenzieschmoll** [comment]
FYI @vlidholt.

**Comment by DanTup** [comment]
I've added some tests and some settings so user can a) turn extension recommendations off entirely and b) replace the allow-list so that authors of packages/extensions could verify their `extension/vs_code` config locally before being in the list.

This is essentially ready to merge (with an empty allow-list), but due to the recent issues with paths, I think we should gate it on an SDK that has `devtools_shared` v6.0.3 that has the fixes.

@kenzieschmoll how is that version bumped in DDS? Is it coming direct from Pub and not via DEPS in the SDK? Do you already have a plan for when to increase it there?

If we're not ready yet, I could merge this with a very high SDK version and we can move it down once we know which Dart SDK we're happy for it to start being used for.

**Comment by kenzieschmoll** [comment]
> This is essentially ready to merge (with an empty allow-list), but due to the recent issues with paths, I think we should gate it on an SDK that has devtools_shared v6.0.3 that has the fixes. How is that version bumped in DDS? Is it coming direct from Pub and not via DEPS in the SDK? Do you already have a plan for when to increase it there?

I rolled the latest DevTools into the Dart SDK yesterday (including your post message fix for the flutter sidebar). And since the DDS dep on devtools_shared is `^6.0.0`, it should already be picking up `6.0.3`.

**Comment by DanTup** [comment]
I was a bit concerned by not having 6.0.3 in the pubspec to enforce this, but I see you've landed https://github.com/dart-lang/sdk/commit/a86eb8bd113b77b07f588d8772ca000897807c33 now so looks like it's safe to use 3.3.0-247 - thanks!

**Pull request merged**
