### PR TITLE
Flutter Outline preview

### PR DESCRIPTION
**Pull request by DanTup**
~~Gonna merge this, but behind a flag with an EXPERIMENTAL note because I think it's kinda unusable without a couple of issues (like https://github.com/Microsoft/vscode/issues/48198)~~.

Fixes https://github.com/Dart-Code/Dart-Code/issues/605.

### CODE REVIEW

**Comment by DanTup** [comment]
Scratch that - this still feels really unfinished to use. And with VS Code now having a nice Outline preview, it just makes things worse!

There are a few issues I've opened in VS Code that might make it possible for us to use the built-in Outline view for this:

https://github.com/Microsoft/vscode/issues/51332
https://github.com/Microsoft/vscode/issues/51334

**Comment by winsonet** [comment]
but why I still can't use this new featuer (Preview: Flutter Outline) in my VS code?

**Comment by DanTup** [comment]
@winsonet can you be more specific - what do you mean you can't use it? Did you enable it in the user settings, and check you have version v3.3 of the Dart and Flutter extensions? See https://dartcode.org/releases/v3-3/#preview-flutter-outline for notes on this.

If you're still having issues, please open an issue with explicit details on what you're seeing and I can take a look.

**Comment by winsonet** [comment]
Yes, I will open an issue for that, thanks!

**Pull request merged**
