### PR TITLE
npm audit fix

### PR DESCRIPTION
**Pull request by domesticmouse**
Hey DanTup, I'm investigating using DartCode extensions inside of GitPod.io, and I noticed that the plugin needed an update.

HTH, brett

### CODE REVIEW

**Comment by DanTup** [comment]
Thanks!

Looks like the GitHub Actions bots aren't working for PRs, so I'll take a look at fixing that next week, or run the tests locally to ensure this doesn't break anything before merging.

**Comment by domesticmouse** [comment]
Sgtm 😄

**Comment by DanTup** [comment]
I think I fixed the GitHub actions, but they didn't run for existing PR, so I'll merge this and if anything needs fixing it up doing it afterwards. Thanks!

**Comment by domesticmouse** [comment]
Thanks @DanTup, much appreciated!

**Comment by DanTup** [comment]
(note: this change was *not* included in the v3.9.1 release I just did - that was a patch for missing icons and I didn't want to add more to it.. if you need a vsix with these included, let me know!)

**Comment by domesticmouse** [comment]
I built my own VSIX for exploring things on gitpod, but i don't think these changes are required for gitpod. It was purely a code cleanliness update.

**Pull request merged**
