### PR TITLE
Generates a class name from the selected file name

### PR DESCRIPTION
**Pull request by MinuteReversal**
Generates a class name from the selected file name](https://github.com/Dart-Code/Dart-Code/commit/dbeb69affcf87b39f5231bca6b019b80e672b20f
`tk_question_extra_data_dto.dart` -> `class TKQuestionExtraDataDto {}`

### CODE REVIEW

**Comment by DanTup** [comment]
I like this idea! Although these snippets are the "old" snippets - usually they come from the server now. I think we should keep these things in-sync, so we should make equivalent changes in the files here:

https://github.com/dart-lang/sdk/tree/main/pkg/analysis_server/test/services/snippets/dart

Are you interested in contributing them there? If not (I know setting up the SDK for contribution is less trivial than here), I'm happy to do it. The snippets are generated in Dart and currently have hard-coded names like `ClassName` but have access to `request.filePath` that contains the filename they're being generated for:

https://github.com/dart-lang/sdk/blob/45d06f2302f93c89545a4e3bf3b852768f8985c0/pkg/analysis_server/lib/src/services/snippets/dart/class_declaration.dart#L24-L28

**Comment by MinuteReversal** [comment]
Yes I'm very interested, I'm trying to modify the code template and its unit tests.

**Comment by MinuteReversal** [comment]
I have submitted a PR for the sinppet.
[Dart lang sdk #53381](https://github.com/dart-lang/sdk/pull/53381)

**Comment by DanTup** [comment]
@MinuteReversal did you see the comments on the PR/Gerrit review? Let me know if anything is unclear or if you need any assistance addressing them.

**Pull request closed without merging**
