### PR TITLE
Add Markdown support to Documentation Comments

### PR DESCRIPTION
**Pull request by RedCMD**
Fix https://github.com/Dart-Code/Dart-Code/issues/4925

image

Simply just `#includes` Markdown

using `meta.embedded.markdown` with `"embeddedLanguages": { "meta.embedded.markdown": "markdown" }`
enables basic language feature support
like `blockComment` and `autoClosingPairs`

### CODE REVIEW

**Comment by Number-3434** [comment]
Thank you!

**Comment by RedCMD** [comment]
How to enable semantic highlighting?
Can't find any references to it anywhere

VSCode has been setup in a way that semantic highlighting should only ever enchance the TextMate grammars
by highlighting things that TextMate just cant (context aware syntaxes etc)
not completly override the entire document

**Comment by Number-3434** [comment]
@RedCMD It's in `settings.json` - <samp>editor.semanticTo</samp>

**Comment by RedCMD** [comment]
I have that setting enabled already

but even when searching through the code in this repo
I cannot find any reference to `SemanticTokensProvider`

as far as I aware, this extension doesn't provide any semantic highlighting

**Comment by Number-3434** [comment]
Do you see any difference when turning semantic tokens on and off?

**Comment by DanTup** [comment]
@RedCMD 

> VSCode has been setup in a way that semantic highlighting should only ever enchance the TextMate grammars
> by highlighting things that TextMate just cant (context aware syntaxes etc)
> not completly override the entire document

Unfortunately it's not that simple. The LSP server (which is generic and not VS Code-specific) is unaware of what textmate grammar the client may have (if it even has one at all) and therefore provides a full set of semantic highlighting tokens. In VS Code, these overwrite anything from the textmate grammar making it essentially disappear. https://github.com/microsoft/vscode/issues/163292 is a request specifically to support what is necessary to handle this without having to add a lot of non-standard / Code-specific implementation to the LSP server.


> but even when searching through the code in this repo
> I cannot find any reference to SemanticTokensProvider
> 
> as far as I can see, this extension doesn't provide any semantic highlighting

Language functionality comes from the LSP server in the SDK (while there are some providers in this repo, they are only for the legacy protocol which is being phased out). The LSP handler for the semantic tokens is here:

https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/lsp/handlers/handler_semantic_tokens.dart

**Comment by DanTup** [comment]
Isn't that essentially the same request as https://github.com/microsoft/vscode/issues/163292?

**Comment by Number-3434** [comment]
It's very similar, except that my version also allows users and themes to declare the overrides, not in the textmate grammar itself.

I would prefer this option for the customisability aspect.

**Pull request closed without merging**
