### PR TITLE
Switch to reading Flutter survey data from the web

### PR DESCRIPTION
**Pull request by DanTup**
Equiv of https://github.com/flutter/flutter-intellij/pull/4449.

@jayoung-lee @pq FYI! I have tested it with my own copy of the JSON file with varying dates (plus updated the automated tests) but please let me know when you have dates for the next survey and update the file, so I can double-check it. Thanks!

### CODE REVIEW

**Comment by DanTup** [comment]
In VS Code we're not previleged enough to be able to run code in the UI thread (we can't even run code in the same *process* as the UI/editor 😁) so that shouldn't be an issue. I can't see anything in that PR, but did you have to change anything for DNS/proxy issues?

If the file can't be fetched in VS Code, it'll just write the connection error/timeout to the dev tools console (and ofc, not show a survey prompt at all).

**Comment by jayoung-lee** [comment]
I have not set the dates for the Q2 survey yet, but I will do so soon (and update the json file) and ping you all. Thanks!

**Comment by pq** [comment]
> did you have to change anything for DNS/proxy issues?

Well, I *tried*.  I think that moving to the platform `HttpRequests` class rather than my hand-rolled URL processing should handle it but need to push out a dev build for testing to be sure.

**Comment by jayoung-lee** [comment]
Alright, the json file is updated with Q2 survey information!

**Comment by DanTup** [comment]
Great, thanks! I tested with dates before and during the dates in there and the prompt appeared when I'd expect. The change will ship in this months release.

**Comment by jayoung-lee** [comment]
Awesome. Thank you, Danny!

**Pull request merged**
