### PR TITLE
tweak the workspace symbols display

### PR DESCRIPTION
**Pull request by devoncarew**
- work towards https://github.com/Dart-Code/Dart-Code/issues/62
- tweak the workspace symbols display

screen shot 2016-08-14 at 7 16 37 pm

screen shot 2016-08-14 at 7 17 17 pm

The results are for running in the VSCode Insiders (nightly) build. This uses `package:foo/bar.dart` for package libraries, uses relative paths for other libraries, and displays the container hierarchy in the name for elements (`Foo.bar` for class members; `foo` for top-level symbols).

### CODE REVIEW

**Comment by devoncarew** [comment]
Strangely enough, we don't get top-level symbol results for things in `dart:` libraries (`List`, `String`, `Future`, ...).

**Comment by DanTup** [comment]
This looks great!

Do you think we need to make the document symbol list (`Ctrl+Shift+O`) look more like this?

How did you get Code to display those dots without stripping stuff?

> Strangely enough, we don't get top-level symbol results for things in `dart:` libraries (`List`, `String`, `Future`, ...).

Maybe we should raise this as a request? (possible [we might end up with a new search API](https://groups.google.com/a/dartlang.org/d/msg/analyzer-discuss/conkKX7XiKI/Qmw7o3baCAAJ)?)

From your screenshot I see my `shouldIncludeResult` isn't working correctly - you have some package stuff starting with underscores - as I understood, they should be filtered out for not being in the project root. Do you know what happened there? (did you possibly have them open from inside the workspace, which maybe made them come back with workspace paths in the search). If so, should I tweak my `shouldIncludeResult` to treat `packages` the same way as things outside the root?

I'll give this a little test and merge tonight. Thanks!

**Comment by devoncarew** [comment]
> Do you think we need to make the document symbol list (Ctrl+Shift+O) look more like this?

Possibly just to convert it to `Class.member` style? We really wouldn't use the `containerName` fields much at all then -

> How did you get Code to display those dots without stripping stuff?

I think this boils down to using the Insiders build. I stil saw the issue w/ the regular stable build. I went back and forth over whether the issue was fixed in Insiders - I'd be interested i what you see locally -

> From your screenshot I see my shouldIncludeResult isn't working correctly - you have some package stuff starting with underscores

I'm not sure why - from looking at the code it looks like the filter should have worked here. The only thing I did differently was to open the parent of the dart project - it's a project that contains both a dart and a java sub-project (https://github.com/dart-lang/vm_service_drivers).

**Comment by DanTup** [comment]
> Possibly just to convert it to Class.member style? We really wouldn't use the containerName fields much at all then

Yeah, probably. It did look good as-is, but I think being consistent is probably better. What do you think?

> I went back and forth over whether the issue was fixed in Insiders - I'd be interested i what you see locally 

Based on comments from MS, it should've been fixed two weeks ago. I'll try Insiders. Maybe worth you re-checking to see if maybe you'd just confused the two (are they visibly different?). If you can still repro on insiders (and it's up-to-date), might be worth commenting back on the MS case (since it's closed now).

> I'm not sure why - from looking at the code it looks like the filter should have worked here.

I've reopened #74 and will take a look, ta.

**Pull request merged**
